cabal-version: 2.4
name: linden
version: 0.0.1.0
license: BSD-3-Clause
license-file: LICENSE.md
maintainer: Mark Karpov <markkarpov92@gmail.com>
tested-with:
  ghc ==9.10.3
  ghc ==9.12.4
  ghc ==9.14.1

homepage: https://github.com/mrkkrp/linden
bug-reports: https://github.com/mrkkrp/linden/issues
synopsis: A formatter for Haskell source code
description: A formatter for Haskell source code.
category: Development, Formatting
build-type: Simple
extra-doc-files:
  CHANGELOG.md
  README.md

source-repository head
  type: git
  location: https://github.com/mrkkrp/linden.git

flag dev
  description: Turn on development settings.
  default: False
  manual: True

library
  exposed-modules:
    Linden
    Linden.Comments
    Linden.Comments.Attach
    Linden.Parser
    Linden.Printer
    Linden.Printer.Body
    Linden.Printer.Combinators
    Linden.Printer.Internal

  hs-source-dirs: src
  default-language: GHC2021
  build-depends:
    base >=4.14 && <5,
    ghc-lib-parser >=9.14 && <9.15,
    syb >=0.7 && <0.8,
    text >=2.1 && <3,

  if flag(dev)
    ghc-options:
      -Wall
      -Werror
      -Wredundant-constraints
      -Wpartial-fields
      -Wunused-packages
      -haddock
      -Winvalid-haddock
  else
    ghc-options:
      -O2
      -Wall

executable linden
  main-is: Main.hs
  hs-source-dirs: app
  other-modules: Paths_linden
  autogen-modules: Paths_linden
  default-language: GHC2021
  build-depends:
    base >=4.14 && <5,
    linden,
    optparse-applicative >=0.14 && <0.20,
    text >=2.1 && <3,

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

  if flag(dev)
    ghc-options:
      -Wall
      -Werror
      -Wredundant-constraints
      -Wpartial-fields
      -Wunused-packages
      -haddock
      -Winvalid-haddock
  else
    ghc-options:
      -O2
      -Wall

test-suite tests
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  build-tool-depends: hspec-discover:hspec-discover >=2 && <3
  hs-source-dirs: tests
  other-modules:
    Linden.CommentsSpec
    Linden.Gen
    Linden.Printer.BodySpec
    Linden.Printer.CombinatorsSpec
    Linden.Printer.InternalSpec
    Linden.Printer.PropertiesSpec
    LindenSpec

  default-language: GHC2021
  build-depends:
    QuickCheck >=2.14 && <3,
    base >=4.14 && <5,
    hspec >=2 && <3,
    linden,
    text >=2.1 && <3,

  if flag(dev)
    ghc-options:
      -Wall
      -Werror
      -Wredundant-constraints
      -Wpartial-fields
      -Wunused-packages
      -haddock
      -Winvalid-haddock
  else
    ghc-options:
      -O2
      -Wall
